config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/info',   to: 'static_pages#info'
  get '/photos', to: 'static_pages#photos'
  get '/photo',  to: 'static_pages#photo'
  get '/albums', to: 'static_pages#albums'
  get '/album',  to: 'static_pages#album'
  root 'static_pages#home'
  resources :static_pagess
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'will_paginate/array'

  def home
  end

  def info
    begin
      if params[:find_by].key?("id")
        person = Flickr.people.find(params[:find_by][:id])
      elsif params[:find_by].key?("username")
        raise NoMethodError if params[:find_by][:username] == '' # Flickr user exists with username == '', but has no photos!
        person = Flickr.people.find_by_username(params[:find_by][:username])
      end

      @sets = person.get_sets
      @info = person.get_info!

    rescue StandardError => e
      if params[:find_by][:id] == ''
        form_error("Error: user ID cannot be blank")
      elsif params[:find_by][:username] == ''
        form_error("Error: username cannot be blank")
      else
        form_error("#{e.class}: #{e.message}")
      end
    end
  end

  def photos
    id = params[:show][:user_id]
    person = Flickr.people.find(id)
    @info = person.get_info!
    count = @info.photos_count
    get_photos(count, &lambda{|p| return Flickr.photos.search(user_id: id, page: p, per_page: 500).map(&:medium500!)})
  end

  def albums
    @id = params[:show][:user_id]
    person = Flickr.people.find(@id)
    @sets = person.get_sets
  end

  def album
    @title = params[:album][:title]
    person = Flickr.people.find(params[:album][:user_id])
    sets = person.get_sets
    set = sets.detect {|e| e.title == @title}
    count = set.photos_count
    get_photos(count, &lambda{|p| return set.get_photos(page: p, per_page: 500).map(&:medium500!)})
  end

  private

    def form_error(error)
      flash[:error] = error
      redirect_to root_path
    end

    def get_photos(count, &api_search)
      @photos = []
      pages = (count / 500.floor) + 1

      pages.times do |i|
        page_n = i + 1
        result = yield(page_n)
        result.each do |e|
          @photos << e
        end
      end

      @photos = @photos.paginate(page: params[:page], per_page: 100)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "findr", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "find", root_path, id: "hdr_link" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApi</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,900" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <div style="height:30px;"></div>
      <%#= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/static_pages/_show_photos.html.erb
<div class="dark">
  <div class="hidden-lg hidden-md digg_pagination">
    <%= will_paginate @photos, inner_window: 0, outer_window: 0 %>
  </div>
</div>

<div class="hidden-sm hidden-xs digg_pagination">
  <%= will_paginate @photos, inner_window: 3, outer_window: 1 %>
</div>

<div class="hidden-lg hidden-md"  style="width:100%;">
  <div class="row">
      <% @photos.each do |photo| %>
        <%= link_to "http://flickr.com/photo.gne?id=#{photo.id}" do %>
          <%= image_tag photo.source_url, class: 'img-responsive center' %>
        <% end %>
      <% end %>
  </div>
</div>

<div class="hidden-sm hidden-xs center-box">
  <% @photos.each do |photo| %>
    <%= link_to "http://flickr.com/photo.gne?id=#{photo.id}" do %>
      <%= image_tag photo.source_url, size: "#{photo.width}x#{photo.height}", class: 'photo' %>
    <% end %>
  <% end %>
</div>

<div class="hidden-lg hidden-md digg_pagination dark" style="display:block;">
  <%= will_paginate @photos, inner_window: 0, outer_window: 0 %>
</div>

<div class="hidden-sm hidden-xs digg_pagination">
  <%= will_paginate @photos, inner_window: 3, outer_window: 1 %>
</div>

app/views/static_pages/album.html.erb
<h4><%= "#{@title}" %></h4>

<%= render 'show_photos' %>

app/views/static_pages/albums.html.erb
<h4><%= "Albums:" %></h4><br>

<% @sets.each do |set| %>
  <h4><%= "#{set.title}" %></h4>
  <div style="height:5px;"></div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(:album, url: album_path, method: :get) do |f| %>
        <%= f.hidden_field :set_id, value: set.id %>
        <%= f.hidden_field :title, value: set.title %>
        <%= f.hidden_field :user_id, value: @id %>
        <%= f.submit "view album", class: "btn btn-primary album" %>
      <% end %>
    </div>
  </div>
  <br>
<% end %>

app/views/static_pages/home.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type} center") %>
<% end %>

<h4>Find any Flickr user's photos and info.</h4>
<h4>Search using any valid details,</h4>
<h4>or just use a suggested value.</h4>
<div style="height:20px;"></div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="center form">
      <%= form_for(:find_by, url: info_path, method: :get) do |f| %>
        <%= f.text_field :id, class: 'form-control field', value: "24448805@N07", label: "id" %>
        <%= f.submit "find by user ID", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<h4>OR</h4>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="center form">
      <%= form_for(:find_by, url: info_path, method: :get) do |f| %>
        <%= f.text_field :username, class: 'form-control field', value: "Tony Shi Photos" %>
        <%= f.submit "find by username", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/info.html.erb
<h4><%= "Flickr user:" %></h4><br>
<h4><%= "username: #{@info.username}" %></h4>
<h4><%= "real name: #{@info.real_name}" %></h4>
<h4><%= "user ID: #{@info.id}" %></h4>
<h4><%= "total public photos: #{@info.photos_count}" %></h4>
<h4><%= "number of public albums: #{@sets.length}" %></h4>

<div style="height:20px;"></div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:show, url: photos_path, method: :get) do |f| %>
      <%= f.hidden_field :user_id, value: @info.id %>
      <%= f.submit "view all photos", class: "btn btn-primary info" %>
    <% end %>
  </div>
</div>
<div style="height:20px;"></div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:show, url: albums_path, method: :get) do |f| %>
      <%= f.hidden_field :user_id, value: @info.id %>
      <%= f.submit "view album(s)", class: "btn btn-primary info" %>
    <% end %>
  </div>
</div>

app/views/static_pages/photos.html.erb
<h4><%= "All photos:" %></h4>

<%= render 'show_photos' %>